name: Masth_GURU
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1

environment:
  #sdk: ">=2.11.0 <3.0.0"
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_datagrid: ^22.1.36



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_signin_button: ^2.0.0
  font_awesome_flutter: "any"
  #emoji_feedback: ^0.1.0
  google_nav_bar: ^5.0.6
  url_launcher: ^6.1.4
  line_icons: ^2.0.1
  rxdart: ^0.27.4
  english_words: ^4.0.0
  #material_floating_search_bar: ^0.3.7
  flutter_phone_direct_caller: ^2.1.1
  flutter_windowmanager: ^0.2.0
  mailer: ^6.0.1



  #emoji_feedback: ^0.1.0
  #flutter_facebook_auth: '^3.5.0'
  google_sign_in: ^6.1.4
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  intl: ^0.18.1
  firebase_core: ^2.14.0
  shared_preferences: ^2.0.15
  flutter_svg: ^2.0.7
  basic_utils: ^5.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/masti_with_circle.png"
    
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
          - assets/masti_with_circle.png
          - assets/images/masti.png
          - assets/fonts/Century Gothic.ttf
          - assets/images/sos_circle.png
          - assets/images/good.png
          - assets/images/sad1.png
          - assets/images/terrible.png
          - assets/images/happy.png
          - assets/images/neutral.png


          - assets/images/calendar-5-512.png

          - assets/images/terrible.png
          - assets/images/happy.png
          - assets/images/emoji1.png
          - assets/images/emoji2.png
          - assets/images/emoji3.png
          - assets/images/emoji4.png
          - assets/images/emoji5.png
          
          - assets/images/sad1.png
          - assets/images/neutral.png
          - assets/images/good.png
          - assets/images/calendar-5-512.png
          - assets/images/linkedin.png
          - assets/icons/instagram.png
          - assets/icons/facebook.png
          - assets/icons/email.png
          - assets/icons/google.png
          - assets/images/search.png

           
  fonts:
          - family: Century Gothic
            fonts:
               - asset: fonts/Century Gothic.ttf
                 weight: 400  
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
