// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxi8QihF5p7y5c09uX3C2QCU26WFtDgwg',
    appId: '1:314212303311:android:c2b3285cda0b5f164d52ba',
    messagingSenderId: '314212303311',
    projectId: 'masth-life-app',
    databaseURL: 'https://masth-life-app-default-rtdb.firebaseio.com',
    storageBucket: 'masth-life-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN4lM7NpidXO_BdmLDEJqXRbVj7JNnVik',
    appId: '1:314212303311:ios:7708ade28f5a11464d52ba',
    messagingSenderId: '314212303311',
    projectId: 'masth-life-app',
    databaseURL: 'https://masth-life-app-default-rtdb.firebaseio.com',
    storageBucket: 'masth-life-app.appspot.com',
    androidClientId: '314212303311-1ra3u3k0v07140n8ikgkp3qd15r48ba1.apps.googleusercontent.com',
    iosClientId: '314212303311-ikqn93k7517uj3l3jds5dd69anfnkobq.apps.googleusercontent.com',
    iosBundleId: 'com.masth.masthGuru',
  );
}
